# Generated by Django 5.0.7 on 2024-07-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_student_id_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
