# Generated by Django 5.0.7 on 2024-07-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_subject_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='grade',
        ),
        migrations.AddField(
            model_name='examresult',
            name='marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Exam Name'),
        ),
    ]
