# Generated by Django 5.0.7 on 2024-07-30 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_roomschedule'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomschedule',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('event', 'timetable')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
