# Generated by Django 5.0.7 on 2024-07-30 17:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_roomschedule_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and Time'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('date_time', 'room')},
        ),
        migrations.DeleteModel(
            name='RoomSchedule',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
