# Generated by Django 5.0.7 on 2024-07-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='marks',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
